### ISSUE TITLE
radioのdescriptionをプレーンテキストで返す

### ISSUE THREAD

**Issue by taira120** [kure-kosen/cho_kure_web#100]
MDからHTMLの変換がうまくいってない(仕様)のでプレーンテキストで返す

**Comment by euglena1215** [comment]
どのへんがうまくいってないんだっけ？

**Comment by chanyou0311** [comment]
![image](https://user-images.githubusercontent.com/12185831/34291978-306b6a3c-e742-11e7-8914-131784b4038b.png)

http://www.stg.kure-rad.io/

このあたりだそうです。

**Comment by euglena1215** [comment]
vue側でhtmlにparseするのかと思ってた
htmlに変換した状態でjsonで返した方がいい？

**Comment by taira120** [comment]
サーバーで変換したほうがやりやすいのでその方向で行きましょう
