### ISSUE TITLE
vueのroutingを/app以下に変更する

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#108]
vue route nest で検索したらいい感じにできそうだったのでそうする。

理由
vueのhistory modeを使うにはrailsでいい感じにroutingしないとRouting Errorになる。
正規表現で"app"が含まれてるアクセスを全てvue用のcontrollerに投げればうまくいきそう。

**Comment by euglena1215** [comment]
"/"を"/app"にリダイレクトさせるようにするのも忘れずにやる。

**Comment by chanyou0311** [comment]
@euglena1215 historyモード使わない方針にしようかと今日 @taira120 と話したのですが、いかがでしょうか

**Comment by taira120** [comment]
理由は、例えばhistoryモードで`/contact`をブックマークしてた場合、ブックマークからアクセスしたらルートにリダイレクトされることです

**Comment by euglena1215** [comment]
`/` にアクセスした瞬間に `/app` にredirectされるのでその心配はないと思います
きちんとhistory modeを使って `/app/contact` にアクセスすれば問い合わせフォームに遷移されるはず

**Comment by taira120** [comment]
`/app/.*`を`/app`にリダイレクトするなら無理じゃないですか?

**Comment by euglena1215** [comment]
> /app/.*を/appにリダイレクトするなら無理じゃないですか?

しないよ？
リダイレクトするのは / -> /appだけ
```
namespace :front, path: "/" do
  root :to => redirect("/app")
  get "/podcast", to: "podcast#index"
  get "/app.*", to: "root#index"
end
```
こうです
