### ISSUE TITLE
現状の見た目の最適化

### ISSUE THREAD

**Issue by chanyou0311** [kure-kosen/cho_kure_web#152]
- ラジオ詳細のパーソナリティのアイコンがめっちゃ小さい
- アイコンの解像度上げる #182 で対応
- リンクがリンクだとわかるように変更する #187
  - 押せる感
  - Semantic-UIのItemリンクがちゃんと効いていないので修正する

**Comment by kobakazu0429** [comment]
Reactへ移行するのでクローズ
