### ISSUE TITLE
「購読する！」ボタンを追従させる

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#163]

**Comment by chanyou0311** [comment]
#165 が終わった後に着手する

**Comment by chanyou0311** [comment]
@euglena1215 すみませんお願いします

**Comment by euglena1215** [comment]
![2018-01-22 22 02 50](https://user-images.githubusercontent.com/13253769/35223561-258e02b4-ffc5-11e7-9105-48411ca64e56.png)
「Podcastを聞いてみる？」を押すとhow-to-use-podcastに移動

![image](https://user-images.githubusercontent.com/13253769/35225664-466a819a-ffcc-11e7-8a12-d48b4c43f79f.png)
「Podcastを起動する」がpodcastを開くリンク

**Comment by euglena1215** [comment]
こんなイメージでやってみる
