### ISSUE TITLE
ラジオの詳細ページから他のラジオの詳細ページに移っても内容が更新されない

### ISSUE THREAD

**Issue by taira120** [kure-kosen/cho_kure_web#189]
パーソナリティも同じ

**Comment by kobakazu10** [comment]
「ちょっくれとは？」→「Podcastってなんだ？」という方は[こちら](http://www.kure-rad.io/app/how-to-use-podcast/)で説明していますので～、も同じ

F5で更新すればいけるけど

**Comment by chanyou0311** [comment]
`about` から `how-to-use-podcast` は、 `<router-link>` を使えば直りそう
