### ISSUE TITLE
ブラウザの戻るボタンを使って戻ると何も表示されない

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#206]
ブラウザの戻るボタンを使って戻ると何も表示されない。
更新するときちんと更新される。

**Comment by chanyou0311** [comment]
@kure-kosen/cho_kure_radio これ、OSXのChromeじゃ戻るボタン効くんだけど、動作しない環境って何なんだろう？

**Comment by kobakazu0429** [comment]
Reactへ移行するので一旦クローズ
再発時にリオープン
