### ISSUE TITLE
「ちょっくれとは」からpodcast登録方法へのリンクが切れてる

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#218]

**Comment by chanyou0311** [comment]
@kobakazu10 これ、一行書き換えるだけでOKなissueなので、一番最初に手を付けるissueとしていいかも！

**Comment by chanyou0311** [comment]
@kobakazu10 
こちら参考にやってみてもらえる？？

https://github.com/kure-kosen/cho_kure_web/blob/4f29cb278c2c5739fc92ae8af6c0669cf78125d7/frontend/src/packs/root.js#L52-L61

https://github.com/kure-kosen/cho_kure_web/blob/4f29cb278c2c5739fc92ae8af6c0669cf78125d7/frontend/src/pages/about.vue#L17

**Comment by kobakazu10** [comment]
@chanyou0311 
これってブランチ切りますか？

**Comment by chanyou0311** [comment]
@kobakazu10 もちろん切ります！
ブランチ名は他のを参考にしてみてください！

**Comment by chanyou0311** [comment]
`feature/create-jargon-api` など！ `feature/hogehoge` で！

**Comment by kobakazu10** [comment]
@chanyou0311 
fix/how-to-use-podcast-link
とかじゃなくてfeature/のほうがいいですか？

**Comment by chanyou0311** [comment]
@kobakazu10 ごめん、その通りです！ `fix/xxx` が正しいです！

WIPラベルは、ブランチを切った後に空コミットをしてプッシュして、プルリク立てたものに付けてください！！

**Comment by chanyou0311** [comment]
こんな感じ
https://github.com/kure-kosen/cho_kure_web/pull/231

**Comment by chanyou0311** [comment]
https://qiita.com/NorsteinBekkler/items/b2418cd5e14a52189d19

`git commit --allow-empty -m "empty commit"`
空コミットこれでできるかと！
