### ISSUE TITLE
パーソナリティ一覧

### ISSUE THREAD

**Issue by taira120** [kure-kosen/cho_kure_web#333]
# パーソナリティ一覧
- パーソナリティ
    - 一回だけ出た人と，そうでない人を分ける

**Comment by kobakazu0429** [comment]
`api/v2/personalities/` に

?count => number
?random => boolean?

を生やして欲しいです

**Comment by kobakazu0429** [comment]
SNS ID(URL)カラムを増やす
- twitter
- facebook
- instagram
