### ISSUE TITLE
production環境をstaging環境として使ってしまってる問題

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#36]
production環境とは
* 本番のデータが入っている
* 実際のユーザーに使われるための環境
* これを作るために日々がんばる。

staging環境とは、
* 設定はproduction環境とほぼ一緒
* データはサンプルのものが入っている
* サーバ上でも(AWS周りとかOSのズレなど)きちんと動作するかチェックしたり
* 非開発者の人に見てもらって意見をもらうために使う

現在はproductionとしてはいるものの、完全にstaging環境として使っている。
今のところはいいんだけど実際にリリースするときはちゃんとしたproduction環境を作らないといけない。

なのでAWSポチポチしてもういっこEC2とS3をたてる。

**Comment by euglena1215** [comment]
https://qiita.com/naoki_mochizuki/items/f795fe3e661a3349a7ce

**Comment by taira120** [comment]
stagingを立てる
