### ISSUE TITLE
誰でもパーソナリティ登録ができてしまう

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#39]
現状として誰でもsignupができるためadminの中身を誰でも見られる状況になっている。

いい感じに限られた人だけsignupできるようにしたい。

今のところ考えてるのはsignupページにbasic認証をかけてそのパスワードを
ちょっくれの人に聞かないとsignupページに到達できないようにする。

**Comment by euglena1215** [comment]
@chanyou0311 
なんかいい案ないですかー

**Comment by taira120** [comment]
signupのapi消して手動登録じゃだめなんですか？

**Comment by euglena1215** [comment]
メアドを聞いてちょっくれメンバーで手動仮登録をして後で修正してもらうってことよね？
確かにそれが他の人から見られる心配がなくていいかも

**Comment by taira120** [comment]
ですねー
それかconfirmationがdeviceにあったと思うのでそれを使っていい感じにするとか

**Comment by chanyou0311** [comment]
メールアドレスはフォーム経由でスプレッドシートにまとめてあるので、そのアドレスで仮登録するのが良いかと思います。

**Comment by euglena1215** [comment]
@taira120 
> それかconfirmationがdeviceにあったと思うのでそれを使っていい感じにするとか

いい感じとは？

productionでmailerの設定めんどくせえってなって今confirmable切ってる
と思ったけど、password忘れたときの確認メールは送られるはずだからmailerの設定いるわ
試したら普通に500返ってきて死んでた

**Comment by taira120** [comment]
@euglena1215 
confirmationをメールじゃなくて手動でやればいいかなってことです

**Comment by euglena1215** [comment]
@taira120 
confirmationで送られるメールの送信先をcho.kure.radioにして俺ら側でconfirmできる仕組みにするってこと？
それもよいけど

> signupのapi消して手動登録

やっぱこれが一番実装楽な気がするのでこれでいこうと思います！
(deviseの内部に手を入れたら闇を見そうな気がするのであまり近づきたくないというのはある)
