### ISSUE TITLE
RadioのCRUD

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#4]
/admin/radiosからCRUDができるようにする。

## やること

1. [DB設計](https://docs.google.com/spreadsheets/d/1jf_5nvy1fqzAiuNWUXJ0HeHU0m39OLtxUcNNbB0awyw/edit?usp=drive_web) を元にコマンドでmodelを作成する
2. `rails g scaffold_controller admin/radios --model-name=radio` (間違ってるかも) でcontroller, viewの雛形をつくる
3. ルーティングを設定する
4. localeファイルを作成する(`radio.ja.yml` 的なやつ)
5. jsonは表示しなくていいのでcontoller, viewからjsonを消す
6. viewを修正する
    1. form, index, showにcolumnがないと思うので追加する
    2. personalityとかみてbootstrapを適用する
7. db/fixturesにseedファイルを作成する
8. layouts/adminのnavにradio一覧を追加する
9. 適宜テストを書く

**Comment by euglena1215** [comment]
@taira120 
とりあえずめちゃくちゃザックリ書いてみたんだけど、どのステップがやることをイメージできなさそう？？

**Comment by taira120** [comment]
@euglena1215 
6がわからないです

**Comment by euglena1215** [comment]
@taira120 
さすがに雑すぎたわw
漏れがあるかもだけどパッと思い出せるのはこんな感じかな
