### ISSUE TITLE
権限をしっかり整備する

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#40]
パーソナリティの中でも管理者、編集者、ゲストの3つに分ける必要があると思ってる。
どの役割の人にどこまでの権限を与えるのかを考えて実装する。

punditとか使えばできそう。

**Comment by euglena1215** [comment]
## コミュニティ
* 管理者
  * 閲覧/追加/更新/削除 全ての操作が可能
* 編集者
  * 閲覧/追加/更新/削除 全ての操作が可能
* ゲスト
  * なにもできない

## イベント
* 管理者
  * 閲覧/追加/更新/削除 全ての操作が可能
* 編集者
  * 閲覧/追加/更新/削除 全ての操作が可能
* ゲスト
  * なにもできない

## ラジオ
* 管理者
  * 閲覧/追加/更新/削除 全ての操作が可能
* 編集者
  * 閲覧/追加/更新/削除 全ての操作が可能
* ゲスト
  * 自分の回のみ閲覧可能

## 専門用語
* 管理者
  * 閲覧/追加/更新/削除 全ての操作が可能
* 編集者
  * 閲覧/追加/更新/削除 全ての操作が可能
* ゲスト
  * なにもできない

## パーソナリティ
* 管理者
  * 閲覧/追加/更新/削除 全ての操作が可能
* 編集者
  * 閲覧/追加/更新 が可能
* ゲスト
  * 自分の詳細ページだけ閲覧/更新可能


なにもできないってのは左側のリンクに表示されてなくてアクセスできないって状態をイメージしてもらえれば

**Comment by euglena1215** [comment]
@chanyou0311 @taira120 
こんな感じかなーって
いかがでしょう？

**Comment by taira120** [comment]
管理者 : 開発メンバー
編集者 : 開発メンバー以外のちょくれメンバー
ゲスト : その他

って感じですかね?

そもそもゲストはいらない気がしますが…

**Comment by euglena1215** [comment]
だいたいそんな感じです
そのうちゲストを呼ぶことはあると思うんだよね
そうなったらゲストの枠を作っておくのは必要だと思う

**Comment by taira120** [comment]
ゲストを呼ぶことはあると思いますが、プロフィールが編集できること以外はHPでできることと変わらないと思います。
プロフィールの編集権限はこちらの負担軽減のためですか?
