### ISSUE TITLE
Vueの導入

### ISSUE THREAD

**Issue by taira120** [kure-kosen/cho_kure_web#61]
- vue.js
  - vue-router
  - ~vue-loader~ デフォであった
  - vue-devtools
  - eslint-plugin-vue
- webpacker
  - webpack-dev-server

導入しないもの
- vuex
  > いつ、Vuexを使うべきでしょうか？
  > Vuex は、共有状態の管理に役立ちますが、さらに概念やボイラープレートのコストがかかります。これは、短期的生産性と長期的生産性のトレードオフです。
  > もし、あなたが大規模な SPA を構築することなく、Vuex を導入した場合、冗長で恐ろしいと感じるかもしれません。そう感じることは全く普通です。
  > あなたのアプリがシンプルであれば、Vuex なしで問題ないでしょう。単純な グローバルイベントバス が必要なだけかもしれません。
  > しかし、中規模から大規模の SPA を構築する場合は、Vue コンポーネントの外の状態をどうやってうまく扱うか考える絶好の機会です。

- vueify
  webpackerを使うため

### 参考
ツール
https://github.com/vuejs/awesome-vue

環境構築
https://qiita.com/jnchito/items/30ab14ebf29b945559f6
https://qiita.com/cohki0305/items/582c0f5ed0750e60c951

**Comment by euglena1215** [comment]
* 何を導入できるのか
* そのうちどれを導入するのか
* 導入しない理由, 何が障壁なのか

を明示しておいてもらえると今後考え直すときに役にたつと思うのでその辺お願いします

**Comment by taira120** [comment]
@euglena1215  
何を導入できるのかってのはvueかreactかって言うレベルの話ですか?

**Comment by taira120** [comment]
@euglena1215  
何を導入できるのかっていうのはvueかreactかっていうレベルの話ですか?
それともwebpackerかbrowserifyかみたいな話ですか?

**Comment by euglena1215** [comment]
vueとwebpackerは導入は確定でよいのかなって思う(これを今後入れ替えたりするのは厳しいと思うので)

vueのモジュールをどこまで適用するかって話がメインなのかなと
https://nakajmg.github.io/s/161119-vue/#32

vue-router, vuex, vue-loader, vueify, vue-devtools etc...
このあたりをどこまで初期設定で適用するかなってことを明示してほしい。

入れなかった原因がはっきりしていたら
原因がプロジェクトに依存するもの(そもそもこのプロジェクトには必要ない)なのか
人に依存するもの(学習コストが高い、段階的に入れるべき)なのかがハッキリすると思うので！

**Comment by euglena1215** [comment]
close!!!!!!!!!!!!
