### ISSUE TITLE
robots.txtとsitemapの設定

### ISSUE THREAD

**Issue by euglena1215** [kure-kosen/cho_kure_web#74]
環境ごと(productionとstaging)に適切なrobots.txtとsitemapを与えるために

https://github.com/LaunchAcademy/roboto
https://github.com/kjvarga/sitemap_generator

を導入する。

sitemapを定期的に更新するために
https://github.com/javan/whenever
も入れる。

**Comment by euglena1215** [comment]
@chanyou0311 
sitemapの重要度ってどのくらいなんですかね？

**Comment by chanyou0311** [comment]
@euglena1215 エンドユーザーからみた重要度のこと？
なら、それほど高くないと思います。

**Comment by euglena1215** [comment]
SEOによる「googleで検索したらきちんと上位に表示される」とかを含めたエンドユーザーの諸々の体験を含めたものですね

**Comment by chanyou0311** [comment]
@euglena1215 SEO対策は今後していくべきだろうけど、現状"ちょっくれ"とか"ちょっときいて呉高専"でキーワード検索でちゃんと当たるんで、SEO対策の重要度は高くはないと思っています。
そういったSEO対策の意味も込めてもサイトマップの重要度は中くらい、中の上くらいと思っています。
