### ISSUE TITLE
メインのコンテンツが短すぎたときのフッターを修正

### ISSUE THREAD

**Issue by chanyou0311** [kure-kosen/cho_kure_web#86]
メインのコンテンツが短すぎるとフッターが上に詰めて表示されて汚いので修正する。

![image](https://user-images.githubusercontent.com/12185831/33873978-6a3ecf5e-df60-11e7-9ed2-5fc2b2035bba.png)

こうなる。

**Comment by chanyou0311** [comment]
@taira120 @euglena1215 @srpkdyy どなたか修正してもらえると助かります。

**Comment by chanyou0311** [comment]
参考
https://liginc.co.jp/designer/archives/6435

**Comment by taira120** [comment]
やりまーす

**Comment by chanyou0311** [comment]
これもcloseする
