### ISSUE TITLE
ラジオ詳細記事にVueを組み込む

### ISSUE THREAD

**Issue by chanyou0311** [kure-kosen/cho_kure_web#94]
ラジオ詳細記事にVueを組み込んで動的にコンテンツを表示させる。

Markdownをうまいこと表示させる必要があるね。

**Comment by euglena1215** [comment]
adminのformでのmarkdown表示はRails関係ないのでそこと同じにすれば問題なくいける気がする

**Comment by euglena1215** [comment]
これもらいます

**Comment by euglena1215** [comment]
よくみたらWIPで上がってた
