### ISSUE TITLE
メンバー紹介ページにVueを組み込む

### ISSUE THREAD

**Issue by chanyou0311** [kure-kosen/cho_kure_web#95]
メンバー一覧ページとメンバー詳細ページにVueを組み込む。

**Comment by taira120** [comment]
頂きます

**Comment by euglena1215** [comment]
@taira120 
https://github.com/kure-kosen/cho_kure_web/blob/feature/dev/app/controllers/api/v1/personalities_controller.rb#L3
 `Personality.all` ->`Personality.on_public`  にしてもらえると！

**Comment by taira120** [comment]
`personalities/:personality_id/radios`を生やす
パーソナリティが出演したラジオを返すAPI

**Comment by euglena1215** [comment]
personality_serializerに
`has_many: :radios` を追加すればAPI増やさなくていいと思うよ

**Comment by taira120** [comment]
たしかに

**Comment by taira120** [comment]
@euglena1215  
と思ったんですけど`published_at`とか順番とか最新いくつとか絞りたいのでやっぱり生やしますね
